# Generated by Django 4.1 on 2022-09-01 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_bids_bid_rename_comments_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='definitioan',
            new_name='definition',
        ),
    ]
