# Generated by Django 4.1 on 2022-09-01 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_definitioan_auctionlisting_definition'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
