# Generated by Django 4.1 on 2022-09-06 11:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auctionlisting_watchlist_delete_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='watchlist',
            field=models.ManyToManyField(blank=True, limit_choices_to={True}, related_name='watchlist_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
