# Generated by Django 4.1 on 2022-09-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_alter_auctionlisting_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='max_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
